language: node_js

node_js:
- '8'

addons:
  chrome: "75.0.3770"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

  # Playground dependecies:
  - gem install jekyll
  - gem install jekyll-seo-tag

script:
- yarn build
- yarn test

deploy:
  provider: script
  skip-cleanup: true
  script: bash deploy/deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|latest-release-website)$
