language: node_js

node_js:
- '14'

addons:
  chrome: stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

  # Playground dependecies:
  - gem install jekyll -v 3.8.6
  - gem install jekyll-seo-tag

script:
- DEPLOY_PUBLIC_PATH=/resources/ ENABLE_CLDR=1 yarn build
- yarn test

deploy:
  provider: script
  skip-cleanup: true
  script: bash deploy/deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|latest-release-website)$
