name: auto cancellation running job
on: pull_request

jobs:
  cancel:
    name: auto-cancellation-running-action
    runs-on: ubuntu-latest
    steps:
      - uses: fauguste/auto-cancellation-running-action@0.1.4