name: Deploy Main Playground

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install and Build
      run: |
        yarn install
        yarn build:playground:main_as_admin

    - name: Write version.md
      run: git log -1 &>> packages/playground/dist/version.md

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: packages/playground/dist # The folder the action should deploy.
        target-folder: main
        clean: true

  deploy-to-netlify:
    runs-on: ubuntu-latest
    needs: deploy
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NELIFY_ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: "./packages/playground/dist/main"
