name: Deploy Latest Playground [on push]

on:
  push:
    branches: [ latest-release-website ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'

    - name: Install and Build
      run: |
        export NODE_OPTIONS="--max_old_space_size=4096"
        yarn install
        yarn ci:deploybuild

    - name: Write version.md
      run: git log -1 &> packages/playground/dist/version.md

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: packages/playground/dist # The folder the action should deploy.
        clean: true
        clean-exclude: nightly