name: Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    if: "contains(github.event.head_commit.message, '#prerelease')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        node-version: 12

    - name: Install
      run: yarn

    - name: Build
      run: yarn build

    - name: Auth
      run: npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish to npm
      env:
        NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
        NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        node ./.github/actions/pre-release.js